### ISSUE TITLE
What happens when a species is listed at different sensitivity levels in different provinces? 

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#11]
Most of KwaZulu Natal’s sensitive species do not show up as sensitive on the tool. Ezemvelo KZN Wildlife is concerned as data will not be released without careful scrutiny, but SANBI might. Data from KZN doesn’t get channeled through provincial structures only, for example there is a Custodians of Rare and Endangered Wildflowers (CREW) programme whose data would go directly to SANBI. There needs to be agreement on the concept of sensitivity. After further discussion the following actions were agreed to:

Action: add tickbox to flag species that are at risk of localised extinctions and user to justify.

**Comment by rukayaj** [comment]
Flag species at risk of localized extinction (tickbox)

**Comment by reupost** [comment]
This would be on the 'Population vulnerability' tab, right?  It seems like there would be a Y/N tickbox and also a text area for the justification if Y.

**Comment by reupost** [comment]
Sorry, of course there is already a 'Justification' text area, my bad!

**Comment by reupost** [comment]
Could just amend the text on the 'Population vulnerability' tab:

Population is vulnerable: size is <= 2500 mature individuals OR the number of known subpopulations is <= 5 OR range is <= 100km2 _OR species at risk of localised extinctions_

**Comment by rukayaj** [comment]
Yes good thinking. I've changed it:
![image](https://user-images.githubusercontent.com/9654499/31929366-0a57dfd0-b89c-11e7-9a82-4d208d911bab.png)
