### ISSUE TITLE
A species can be added twice. 

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#14]
Action: ensure species cannot be duplicated

**Comment by reupost** [comment]
Unless you feel like writing a name parser :), it would be good to guide users on how to structure the species name.  For example "Full name including taxonomic authorities (and year in parentheses for animal species).  Indicate subspecies with 'subsp.', varieties with 'var.'."

Given that its going to be taxon experts capturing species within their field, the potential for duplication is probably not so high, but inconsistency in the way names are formatted between one group and another could be an issue.

11 Oct: the option to pick names from a dropdown is probably too much effort given the lack of a definitive list we could use.  I think in the end the Taxon Leads are going to have to police the layout of the names, so we just need to make sure they are briefed as to the stds. expected.  It may be preferred for animal names not to have taxonomic authorities, for example.
