### ISSUE TITLE
Will the tool manage name changes? 

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#15]
Action: SANBI is able to manage name changes. •	Synchronise with taxonomic backbone

**Comment by rukayaj** [comment]
But how do we do this?

**Comment by reupost** [comment]
For now, Brenda has indicated that we shouldn't try to accommodate the taxonomic backbone / info. architecture.  

So any name changes would be made manually, simply by changing the old species name to the current name.  There is no requirement to display synonymous names, or to guide users to the current name, as far as I know.  That would be sensible functionality to add to the taxonomic backbone.
