### ISSUE TITLE
What happens if two people are editing a species at the same time? 

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#16]
Action: when species are being edited, add an icon to say it’s in use and can’t currently be edited.

**Comment by rukayaj** [comment]
I'd need to install this https://www.drupal.org/project/content_lock. I'm slightly concerned it's only alpha. Are there multiple taxon leads per group that are likely to want this do you think?

**Comment by reupost** [comment]
I'd leave this

**Comment by rukayaj** [comment]
Ok cool.
