### ISSUE TITLE
There is no field for public comment

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#17]
Action: include a web application form.

**Comment by reupost** [comment]
Would that then be emailed to SANBI staff (e.g. Brenda)?  I think we need to clarify what happens once someone makes a comment.

**Comment by rukayaj** [comment]
I'm not sure that it was discussed. Maybe the contact form is enough?

**Comment by rukayaj** [comment]
I think we did actually discuss this some time after and we decided that as we don't have a member of staff to administer the comments we're not going to add comments. We can reopen this issue if I need to add it after all.

**Comment by reupost** [comment]
Agreed
