### ISSUE TITLE
Separate justification and references and allow document uploads

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#18]
From workshop notes

**Comment by rukayaj** [comment]
I'd have to change all the javascript and double check the template as well to do this. Budget 3 or 4 hours.

**Comment by rukayaj** [comment]
I think it would actually be way better to have references stored in the database as bibtex or json. Would make it much easier to import/export later. I'd have to have a separate file upload bit for any files they want to upload. I should use this https://github.com/ericpugh/drupal-bibtex-field module.

**Comment by reupost** [comment]
Sounds good, but will the users be able to simply attach a file (e.g. PDF / MS Word)?  I think that is the core functionality they will want.  Not sure how this module works - does it offer this?  The way its stored 'under the hood' is probably less NB at this point.

**Comment by rukayaj** [comment]
I'd need to do the file upload separately I think. I will have a look at the module and see. I still don't have a working dev version of the site, so while thingummy and Brian are working on it I will try get my dev version working.

**Comment by reupost** [comment]
Can you set up the file upload, please?  Its NB that the users can attach docs if needs be.  Let me know if you want to chat through this at all.  At a basic level, as long as they can upload one doc for each justification / reference field I think we'd be 95% of the way there, so it needn't be too complicated.  Does that sound do-able by Mon?

**Comment by rukayaj** [comment]
B + S were saying they needed all the metadata for each document as well, so is that no longer the case? Or do you want me just to do something as a temporary stopgap for the weekend?

**Comment by reupost** [comment]
No, whatever Brenda said is probably still applicable, just there's no space for it on the site and we 'go live' next week :/.  

It seems a waste of effort to build much here if the longer-term idea is to integrate with the dspace(?) engine.  

I think as a stopgap the Taxon Leads would need to ensure that there is a reasonable citation for any files that have been uploaded.  It would be useful if this had a specific place to be recorded, but in a pinch they can simply put at the end of the justification in the main text box I suppose.

**Comment by rukayaj** [comment]
Ok I've added a file upload box that lets you upload multiple files with a description. I've also fixed the thing that wasn't letting you upload files. 

For future reference, had to fix this by doing: https://www.drupal.org/forum/support/post-installation/2016-01-16/file-upload-error-drupal-801
I went into IIS > my drupal site > Authentication > Edit Anonymous Authentication > Check Application Pool Identity - For security reasons had changed my application pool user identity from IUSR to a custom account. I don't know why this fixed it because all accounts. The custom account is locked down like IUSR but for the time being it's fixed.

**Comment by reupost** [comment]
Great, that works nicely - thanks!

**Comment by rukayaj** [comment]
Ok I think we decided with this one that as they didn't mention it in your workshop we were going to not bother doing anything right? Not doing anything about separating justification + references. Correct me if I'm wrong.

**Comment by reupost** [comment]
Yes, lets leave the justifications and references as a single text area for now.
