### ISSUE TITLE
Hide past justification box

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#19]
From workshop notes

**Comment by reupost** [comment]
Not sure where this is?

**Comment by reupost** [comment]
Ok, on the species details page.  The new taxon experts would need to access these details for the process of assembling their revisions, so could it be hidden from non-logged-in users rather?

**Comment by rukayaj** [comment]
I probably need to just go into the template and only print out the past justification box if the user is not logged in. One could do this quite easily in Drupal 7, hopefully it is as easy in D8. I'll budget around an hour for it but it might take only 15 minutes, might take longer.
