### ISSUE TITLE
Species champions

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#20]
From workshop notes: add ‘champions’ who are in charge of groups of species who have the ability to vet/verify certain species. This means that a little verified or whatever icon will appear on the page. But at what point are these chosen for new species? Can you change them? If they are changed does it need to get vetted?

**Comment by rukayaj** [comment]
•	Whenever a change is made to a species page which results in a change in sensitive status, that champion is notified

**Comment by rukayaj** [comment]
•	If 3 years goes by and a species has not been edited, email the champion

**Comment by reupost** [comment]
I'm not sure of the specific discussions behind this, but it might be supplanted.  I'll confirm with Brenda.  The thinking at this point is to have the data entered & vetted by the taxon leads directly.  They would manage the data for their particular group.  

What might be needed is to set up a 'Taxon author' role, who would be able to edit new species pages that they have created, but not species pages created by other users.  That would ensure there was no accidental cross-editing of another expert's work, though I'm not sure it is likely to be a big enough issue to put much time into at this point.  What do you think?

Given the timeframes of this project, and the need to rework things once the Info. Arch. comes into existence anyway, I wouldn't worry about emailing experts after 3 years or after edits have been made.

**Comment by rukayaj** [comment]
I think this is the same as the taxon leads.
