### ISSUE TITLE
Document uploads (for references)

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#21]
•	Add ability to upload documents to the tool

**Comment by reupost** [comment]
I have reservations about setting up another document repository here.  It might be ok in the short term (which is what we're looking at, I guess), but really there should be a way to load them into a central repository with appropriate metadata.  

The central SANBI one at http://www.sanbi.org/information/documents is not ideal from a workflow perspective (the expert would need to send the doc to someone in BIM, who would then have to upload it and afterwards send back the link to put into the justification/references section, which is tedious).

**Comment by rukayaj** [comment]
Ok so I think we decided I was just going to go ahead and implement this right? But not to capture metadata? It might take a bit of fiddling on the server so will budget 2 or 3 hours or so.

**Comment by reupost** [comment]
Yes, if we can allow doc uploads that would be good.

**Comment by rukayaj** [comment]
I'm merging this with the other issue #18
