### ISSUE TITLE
Listing: clear search

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#24]
Need to be able to quickly clear search criteria and return to full listing.

**Comment by rukayaj** [comment]
Well people can just click on the logo at the top to get to the front page again. But I have added a clear search criteria at the bottom of the search results which is just a link to "/"

**Comment by rukayaj** [comment]
Oops i just broke this.

**Comment by rukayaj** [comment]
Found a much better way of doing it. Clear button is next to the search button now. In case I forget: it's in views > advanced > exposed form style.
