### ISSUE TITLE
Listing: taxonomic group filter

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#29]
To allow taxon experts to see the status of their group as a distinct set, we need a filter.  Filtering on Family name is not a perfect solution though, since many of the groups have multiple families in them.

Ideally, we'd have 'friendly' names that mapped to one or more families, so for example, filtering on 'Beetles' would display all species within the order Coleoptera (including multiple families).  This would require adding another field to expand our current categories of 'plants'/'animals' to cover the following groups (as per the taxon expert categories - each taxon expert will be working in one of these groups):

Marine Fish
Freshwater Fish
Birds
Reptiles
Amphibians
Mammals
Spiders
Scorpions
Butterflies
Beetles
Plants

Let me know what you think.

**Comment by rukayaj** [comment]
In every case except marine/freshwater fish this would be covered by the higher level taxonomy. For the moment I'll put in both these informal groupings + higher level taxonomy. The incorporation into the architecture later on might mean the removal of both of these.

**Comment by rukayaj** [comment]
I think it's going to be a lot of effort for not much reward to do all the higher level taxonomy as that's going to come from BRAHMS/Specify later, so for the moment I've just done families + groups.

To get families for plants I extracted a field view of genus + family + family group from BRAHMS, added it to my spreadsheet and did a vlookup to match each genus to family. 

For families for animals I did a vlookup on the original dataset sent to me, and where name corrections meant that the family wasn't available I looked them up manually. 

For types/groups/categories for animals I manually mapped them. Scorpiones = Scorpions, Coleoptera = Beetles, etc. Diptera seem to be flies, so I added a flies category. It seems very odd to me that flies are sensitive, but anyway. There's also Clypeasteroida which = Sea urchins.

Complete list is therefore: 
Amphibians
Beetles
Birds
Butterflies
Flies
Freshwater fish
Mammals
Marine fish
Plants
Reptiles
Scorpions
Sea urchins
Spiders

What we actually have assessments/data for:

Beetles
Birds
Butterflies
Flies
Mammals
Reptiles
Scorpions
Sea urchins

So we could do away with some types I guess? It's a motley collection. I do think the speciesstatus.sanbi.org way of associating common names with higher taxonomy is a better way of doing this, but I don't think it's going to be worth the time investment. I have a feeling this platform is going to get merged in with the red listing stuff anyway, so I'm aiming here for minimum effort :)

**Comment by reupost** [comment]
Ok, I agree, let's leave the higher taxonomy for now (above family-level).  The species status method is probably good too, but agree we don't need to invest time on this now.

For the new groupings (flies, see-urchins), lets see if they get used.  We can always adjust the text of e.g. the 'butterflies' group to be 'butterflies and flies' (for example) and put the flies in the same set, if the users prefer it that way.  

It seems the old 2010 list is not a very good starting point for the new assessments :(.  This based on feedback from meeting the plant people this morning, and some other experts have also given this input.  So I wouldn't worry too much about what the groups look like based on the existing data.  Let's set up the complete list and see what gets used,
