### ISSUE TITLE
Do we need to differentiate between mature and immature in targeted demographic?

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#3]
One thing in the email below I just want to clear up quickly: 
• Targeted demographics… Tony said: it should impact on the decision tree.  If it is not  either “Immature individuals (seeds, eggs, larvae, etc.) are permanently removed or killed” or “Mature/breeding individuals are permanently removed or killed” then it cannot be a Sensitive Species!  That is the point!  Please fix your decision tree.    (note we cannot test the full decision tree yet: we need the other fields)

This is in the decision tree. Take a look at my ‘english’ code I wrote out for you and you will see it there. It is just I don’t see why we need to differentiate between immature and mature, why don’t we just say “Individuals are killed or significantly weakened” or “Individuals are not killed or significantly weakened” instead of differentiating between mature/immature? 

I understand that from a biological perspective it is quite important to know whether mature or immature are targeted, but according to our decision tree logic it has no bearing on whether something is labelled as sensitive or not. So I was proposing just making it a bit simpler.  Should we do this?

**Comment by rukayaj** [comment]
From workshop notes: Should not just be looking at mature individuals (e.g. turtle eggs), Add option to Targeted Demographics: Immature Individuals are targeted and this significantly impacts mature individuals

**Comment by rukayaj** [comment]
From workshop actions: Add an option to targeted demographics - immature individuals are targeted and this significantly impacts mature individuals.

**Comment by reupost** [comment]
As it stands, the text on the 'Targeted demographics' tab refers to Mature individuals only.  I would suggest changing the options to be (where the first two options mean the same thing, ITO the rules for sensitivity of the species): 

* Mature (breeding) individuals are killed, significantly weakened or are permanently removed from the wild.
* _Immature individuals are targeted and this significantly impacts mature individuals._
* Mature (breeding) _and immature_ individuals are not killed, are not significantly weakened (the harvesting methods do not do harm), and are not permanently removed from the wild.
* Unknown.

**Comment by rukayaj** [comment]
Ok so it looks like this one is done. Thanks Reuben.

**Comment by reupost** [comment]
I'm still seeing 

Mature (breeding) individuals are killed, significantly weakened or are permanently removed from the wild.
Mature (breeding) individuals are not killed, are not significantly weakened (the harvesting methods do not do harm), and are not permanently removed from the wild.

on the 'Targeted Demographics' tab

**Comment by rukayaj** [comment]
Oh sorry I misread what you had put.  Have a look now:
![image](https://user-images.githubusercontent.com/9654499/31929233-7a25df20-b89b-11e7-83cb-f3d5d22f38b6.png)
