### ISSUE TITLE
Species 2010 status missing

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#31]
At present only 3 species are listed as sensitive.  Is this intentional?  If so, is the 2010 sensitive species list available for the taxon experts to refer to?

From meeting Brenda + Selwyn 11 Oct: ok, so all species on the list were originally on the 2010 sensitive list.  
* This needs to be made clear in the 'About' section so that users don't accidentally think species are definitely not sensitive based on their current status now.  
* Also need to allow end-users to download the original 2010 sensitive species list (just the 'species' tab from the species-matching-up-families.xlsx file I think); again a link from the About page should be fine

**Comment by rukayaj** [comment]
Ok I think this is sorted? I added a line to the front page seeing as it's quite important. I still don't know what else needs to go on the about page, see issue #41
