### ISSUE TITLE
Listing for experts: fields

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#32]
On the content listing for logged-in users (http://nssl.sanbi.org.za/admin-content-simple) the following fields should also be included:
Sensitivity
Family
Group

The Date field could omit the timestamp.

**Comment by rukayaj** [comment]
I think it might be useful for the staff to see the time something was edited as well as the date. Say an expert is editing a species, and taxon lead adds some point of discussion or something in the refs, would be useful for him/her to see at a glance when an update has occurred. So I left timestamp in, but added the rest.

**Comment by reupost** [comment]
Ok, that's fine.  I think for general users (i.e. the public listing) let's keep that one simply the date though.
