### ISSUE TITLE
Listing for experts: filters

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#33]
Filtering on 'Rebuttal' does not show the test rebuttal I posted (which I will now delete).

It should also be possible to filter on sensitivity and group.

**Comment by rukayaj** [comment]
Actually it doesn't really make sense to view comments (or rebuttals as we used to call them) in this interface does it? I have taken it out as a search option.

**Comment by reupost** [comment]
Ok, cool.  

'Type/group' is shown twice though, so I'm reopening this one ;)

**Comment by rukayaj** [comment]
Thanks, should be sorted now.
