### ISSUE TITLE
Rebuttals: need ability to edit/delete these

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#34]
These are currently found in the 'Comments' tab of the content listing, but this is only visible to admin-level users.  

I would say given the sensitivity of issuing a rebuttal, that they need to be moderated before being published and experts should also be able to withdraw (delete/unpublish) them.  Possibly rebuttals should in fact only be visible to logged-in users?  Need to discuss this.

**Comment by rukayaj** [comment]
This is covered by #44
