### ISSUE TITLE
Species view: sensitive flag clickable

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#37]
The 'Sensitive' / 'Not sensitive' tag next to the species name is clickable, but it doesn't do anything.

**Comment by rukayaj** [comment]
I've disabled those buttons which does fade them out slightly but I think actually helps them look less like buttons. What do you think?

**Comment by rukayaj** [comment]
Closing this so I know it's dealt with, if you think I need to change it please reopen.
