### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#40]
The page 'http://nssl.sanbi.org.za/contact' looks like it could use a little bit of work.  Maybe simply changing the 'Website feedback' heading to something like 'Would you like to comment on the National Sensitive Species List?' and providing a link to contact BIM directly.

**Comment by rukayaj** [comment]
I've made the heading change. The form should email me at the moment (will add Brenda's email once we've stopped testing). What do you mean by providing a link to contact BIM directly, do you mean a phone number like on BGIS Phone: +27 21 799 8738?

**Comment by reupost** [comment]
I see the 'Contact' form on BiodiversityAdvisor doesn't include phone details, so lets keep things consistent with that and leave it as it is.

**Comment by rukayaj** [comment]
Ok, agreed.
