### ISSUE TITLE
Website context / About

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#41]
It feels like the NSSL website is not integrated within BIM's other offerings at all.  There is no guidance on where the species listing comes from, what authority it has, etc.  Maybe the site needs a basic 'About' page to provide some of this, and include appropriate links to the main BiodiversityAdvisor site.

**Comment by rukayaj** [comment]
The alternative to this is to make the site hidden/login only for the moment. Otherwise the site doesn't make any sense as it is.

**Comment by rukayaj** [comment]
Add full size logo + favicon

**Comment by rukayaj** [comment]
I've added full size logo + favicon. I added a bit more information to the front page explaining what the listing was, but I couldn't think of enough pertinent info to warrant a full separate about page - if there's anything missing and it's lengthy can you send it to me? I can make a separate page then. I have also added a link to BA in the site footer. Closing this issue for now.
