### ISSUE TITLE
Species list download

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#42]
It would be useful for end-users to be able to download the entire list (or the list as per their current filter if that is easier to implement) as a CSV file.  This could then be used by them to update their own databases. The structure could be as simple as <group><family><species name><sensitive>

**Comment by rukayaj** [comment]
I think that I can do this by installing this module https://www.drupal.org/project/views_data_export

**Comment by rukayaj** [comment]
I had to enable/install: Views Data Export, RESTful Web Services, Serialization, Serialization (CSV).

**Comment by rukayaj** [comment]
The UI seems to be broken... I had to spend while fiddling with CSS to get it looking right. No JS changes, all CSS (changed overlying text to transparent, put background image, forced size, etc). If the RSS feed output breaks after this, this will be why.
