### ISSUE TITLE
Rebuttals

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#44]
From discussion with Brenda and Selwyn 11 Oct, it seems like some refinement could be made on rebuttals.

The idea is that the published version of these would be a crafted summary of the internal (taxon lead/expert) discussions.  So maybe the best design would be to have 'rebuttal' being another (rich text) field for the species itself, which could be edited by the taxon leads/experts.  

What are currently called 'rebuttals' could rather be 'comments', which are never visible to non logged-in users.  This would provide the space to capture opinions prior to shaping them into a distinct 'statement of dissent' that would be put into the rebuttal field of the species itself.  And the comments would not need to be editable/deletable (except by the site admin, as currently set up) since they would not ever be visible to the public.  This would simplify things I think.

**Comment by rukayaj** [comment]
Ok, I have: 

1. Created a new long rich text field called rebuttal for species
2. Renamed Rebuttal comments field to just Comments/Comment
3. Removed the ability for anonymous users to see comments (check with http://nssl.sanbi.org.za/species/adenium-swazicum) 

I think this covers everything. I don't think Rebelo will be happy about it though, he wanted to make sure that members of the public knew when there's debate about a particular species and he didn't seem to trust the taxon leads (champions as they were then called) to portray it faithfully. But I think that might just be Tony. Anyway I am closing this issue, please reopen it if anything is broken or it doesn't do what we want.
