### ISSUE TITLE
Re-load of old (2010) list

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#50]
From feedback received this morning (plants and others), there may be limited value in re-loading the 2010 list of species.  The new assessment seems likely to only overlap a little with the old listing, to the extent that it would be more trouble deleting the unneeded entries if the 2010 list were being used as a starting point.

I would suggest that:
(a) we need to make the 2010 list available for download: as-is (i.e.a basic spreadsheet) for the taxon experts, but potentially also in a neater format for public end-users (though this is not urgent) 

and 
(b) we don't need to re-import the list as it currently stands.  It should be archived off in case anyone has added anything, but at this point the experts who were going to do the amphibians haven't started yet, so it should be ok to clear the entire list of species.

**Comment by rukayaj** [comment]
Oh lord! All that work for nothing. Ok I have removed all species again and added it instead as the 2 CSVs which are linked from the landing page once you log in. Members of the public on the front page are asked to download the official 2010 list (which is the same one available from newposa).

**Comment by reupost** [comment]
Lawks, sorry.  I had hoped you hadn't put too much into it.  I hope its saved in an easy format to reimport?  I need to alert Brenda to this change since its quite significant, and its not impossible that she will want to adjust the outcome.

**Comment by rukayaj** [comment]
Yeah it's easy to reimport it all again don't worry.
