### ISSUE TITLE
Attach images

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#52]
Attempt with 1.6MB image gave 'The file phpF291.tmp could not be saved. An unknown error has occurred.
File upload error. Could not move uploaded file.
Image field is required.'

This could be a permission issue on the destination folder.

In a pinch, this could be used as a stop-gap to allow users to upload supporting docs if (a) it could be made to work :) and (b) if the filetypes could be extended to include DOC, PDF, TXT and XLS, say.

**Comment by rukayaj** [comment]
I think this is fixed, reopen the issue if not.
