### ISSUE TITLE
File upload description for new records

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#54]
This is only visible when editing an existing record, not on first entry of the record (before its been saved for the first time).  Please can we make it visible on first entry too.

**Comment by rukayaj** [comment]
Are you talking about the description box? It seems to be appearing for me on first entry of a record (before it has ever been saved). See here 

![image](https://user-images.githubusercontent.com/9654499/32218208-e0e8b7a4-be32-11e7-806b-471d18cb9234.png)

Come find me and show me after your meeting, if you have time.
