### ISSUE TITLE
Species page author to be displayed

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#55]
Could we include the username of the creator (not latest editor) of a particular taxon page?  Best place would be directly under the taxon name, right aligned on the page, smaller font.  We will structure the usernames as '[Surname][Initial]' so that it looks reasonable.  Is that ok?  Sorry about these last-minute tweaks!

**Comment by rukayaj** [comment]
I have set it to be to be "Author: xx" because it looks a bit weird to me when it's just their names.

**Comment by reupost** [comment]
Sorry, would you mind changing the label from 'Author name:' to 'Assessor:'?

**Comment by rukayaj** [comment]
Ok done
