### ISSUE TITLE
Species status

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#60]
At the moment a species is either sensitive or not-sensitive. This needs to be amended to allow for species that are on the website (e.g. bulk-loaded) but not yet assessed.

I think the most flexible arrangement would be to allow statuses as follows:
Sensitive
Not sensitive
Not assessed - assumed not sensitive
Not assessed - assume sensitive until formal assessment

Sorry, the last two are quite clumsy - if you can think of a better phrasing please do! :).  The idea is that some species might be bulk loaded with no intention of doing a proper assessment, since they are assumed to be non-sensitive but loaded really just to reassure users that they have been considered (albeit briefly!), while others might be pending a planned assessment, and by a precautionary approach would be assumed to be sensitive until this is conducted.

**Comment by rukayaj** [comment]
This one can be left for a while, does not need to be done for next week.

**Comment by rukayaj** [comment]
This is covered in the other issue, so closing this issue.
