### ISSUE TITLE
Include 2010 status for species

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#61]
The idea is to include the 2010 assessed status for matching species. The text could appear under the 'Assessor' on the right of the view-species pane, and be phrased something like '2010 status: Sensitive' where the species was on the 2010 list, or '2010 status: Not sensitive' if it wasn't.

I will clean up the 2010 list to include authorities for animals, since this will allow a simple text match on the names (the workshop decided to include the authorities in their new assessments).

Does that sound ok?

**Comment by rukayaj** [comment]
Ok so from the sounds of it we ARE doing the bulk loading, it's just it will populate a new field with 2010 status as sensitive/not sensitive? And we're not populating any of the other fields from the 2010 status right?

**Comment by reupost** [comment]
The way I thought of it, we would keep the 2010 list in a separate, non-updateable table.  It is possible that some new species will be bulk-uploaded (more on that later), but they wouldn't generally be based on the 2010 list, and the 2010 list doesn't have any of the attributes we are using this time round. And in general we don't want to display the 2010 species as-is, rather just indicating if a newly assessed species had a status in 2010.  Some 2010 entries might not even be assessed this time round.

When a species is added / updated on the new assessment list, check if it matches to an existing species in the 2010 list and tag accordingly.  Alternatively check the match on-the-fly when displaying a species, it doesn't really matter - though this would probably make it easier if we identify any missing species or other glitches in the 2010 list and need to tweak it.

What do you think?

**Comment by rukayaj** [comment]
Hmm. Ok so the 2010 list would just be an internal list the system checks every time a new species is saved for the first time? What would it check against, species? + family? I'm thinking just have a static csv ont he server with the 2010 species listed in there and get the system to check against that every time. 

Also, when do i need to do this by?

**Comment by reupost** [comment]
Yes, that sounds perfect: just check the internal list every time the new species is saved and tag if it matches.  I think family + species would be a robust match.  If we were really trying to be useful, the site might warn you if the species matches but the family differs, but I'd say that is a 'nice to have' for now.

I can prepare the composite CSV with the 2010 plants and animals.

We'd like users to be able to start working on the site next week, but let's chat today, if you have a minute, and see what's doable.

**Comment by rukayaj** [comment]
I've updated the list on the front page with your new list

**Comment by rukayaj** [comment]
I've just realised it's not going to work to just do it the first time a node is saved, because users can edit the name of a species. So it's going to have to check every time a node is saved.

**Comment by reupost** [comment]
Sounds good :)

**Comment by reupost** [comment]
Would you mind equalising the font size of the "Sensitive in 2010 **Yes**" text - at the moment the Yes/No indicator is small and almost looks like a superscript.  If you could do the same for the Family as well that would be good!

I can't seem to trigger sensitivity for a plant species.  Not sure if this is enabled yet?

**Comment by rukayaj** [comment]
Hmm. Ok just had a quick squizz and it looks like the plants names had a bizarre amount of spaces on the end of them somehow. I corrected that and I've just checked with Bonatea lamprophylla (Orchidaceae) and it seems to be working now. 

Can do on the font size (I saw it and just hoped nobody would care enough to make me work out what the heck is going on with that CSS). Won't be disruptive so will prioritise the other tasks though.

**Comment by reupost** [comment]
Great stuff :).  Are you using the revised plant list, btw?  Either the one from this morning or the cleaned-up version with naked and full names I emailed on 8 Nov (both are essentially the same).  It would be useful if the site checked against both naked and fully-authorised names (could simply copy-paste the second set of full names under the first naked names).

**Comment by rukayaj** [comment]
Ah thanks for the reminder, will swap it to use the new one you emailed this morning and do the copy/paste thing of the clothed (hehe) names.

**Comment by rukayaj** [comment]
Ok. So the list is updated and the CSS is fixed I think, reopen if there's an issue.
