### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#64]
When I am logged in as a taxon lead ('TestExpert') I cannot view species saved by other taxon leads.  I get 'Access denied' on e.g. http://nssl.sanbi.org.za/species/testing-removal-related-species .  I can edit the record, however.  I can see records saved by an administrator.

Logged-in users need to be able to view all species records so that they can make comments on them.

**Comment by rukayaj** [comment]
Ok this one I think i need to try do asap as it might cause downtime. Just one thing, when you say logged in users need to be able to view all species records (not just their own), do you mean taxon leads or all authenticated users?

**Comment by reupost** [comment]
Both would need to be able to do this so that they can comment on others' assessments.

**Comment by rukayaj** [comment]
And one logged-in user shouldn't be able to edit something that isn't their own content right? But taxon leads should be able to edit all content, not just their own?

**Comment by rukayaj** [comment]
Ok, can you check this? I think it's working the way it should now. 
Logged in users (including taxon leads) can view all unpublished content.
Logged in users can edit their own unpublished content.
Taxon leads can also edit any unpublished content.

**Comment by reupost** [comment]
Yep, that would be good!

On 14 Nov 2017 14:17, "Rukaya" <notifications@github.com> wrote:

And one logged-in user shouldn't be able to edit something that isn't their
own content right? But taxon leads should be able to edit all content, not
just their own?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rukayaj/ssp/issues/64#issuecomment-344272024>, or mute
the thread

**Comment by reupost** [comment]
I'm finding a taxon lead can edit published content, but otherwise its looking perfect.

I'd say leave this as-is for now, we can manage any edits to published species and if it becomes a problem we'll amend.

**Comment by rukayaj** [comment]
Ok cool.
