### ISSUE TITLE
Publicly downloadable 2010 list

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#66]
Please replace the file downloadable here: http://biodiversityadvisor.sanbi.org/wp-content/uploads/2012/09/sensitive_species_list_2010_edited.xlsx with 
[sensitive_species_list_2010_all.xlsx](https://github.com/rukayaj/ssp/files/1470329/sensitive_species_list_2010_all.xlsx)

This one has animals + plants, instead of plants only, and minor other fixes to remove 2 duplicate plant entries.

**Comment by rukayaj** [comment]
Ok, done this. I wasn't able to keep the filename because Brenda seems to be too busy to send me the FTP password to the wp site.
