### ISSUE TITLE
Dates: user 'last access' and content 'updated'

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#68]
I know some of this may be cached and so not up-to-the-minute accurate, but I recall you mentioning there was something funny about the dates shown on the site.  Brenda swore she had not logged into the site on 15 Nov, which was the date assigned to some test content of hers (now deleted, I'm afraid).  

Perhaps the site only records when someone logs out, so the dates can be odd if they have multi-day sessions (if they log-in but then never explicitly log-out).  Any ideas?

Not urgent, but as we are trying to get the users to work on the site some indication of their activity would be useful.

**Comment by rukayaj** [comment]
Oh yeah. I’ve been using her account as my test account, which is why that date appeared. But I think there is something wrong with the dates as well.

**Comment by rukayaj** [comment]
Hmm I didn't change anything but it does seem to be working now. To test it I logged in with Jeff's account, and it's correctly showing last activity as a few minutes ago.  It says you last logged in 6 hours ago, is that about right?

I think that it just is confused about how long people have been a member of the site for. I definitely didn't add Jeff 3 weeks ago, he's had an account pretty much from the start of the site a year ago. Perhaps it calculates that based on when the site was last restored from a backup somehow?

**Comment by reupost** [comment]
Yes, it was looking fine when I tried logging in and creating content as well.  Maybe its something to do with the server, but let's leave this until we find a specific problem.  Maybe use the 'TestExpert' account (or make another one) if you need to test, to avoid confusing Brenda :)

**Comment by rukayaj** [comment]
Following Selwyn's email, I found that what's happening is the people list is getting cached. If we want to see updated dates for that listing, we need to clear the cache, here: 

http://nssl.sanbi.org.za/admin/config/development/performance

**Comment by reupost** [comment]
Great - well sleuthed! :).  So if we want to refresh these details we simply clear the caches. I will relay on to Selwyn et al.

**Comment by rukayaj** [comment]
https://www.drupal.org/project/drupal/issues/2650768 here's the issue thread so we can monitor
