### ISSUE TITLE
Add names of more assessors and authors per assessment

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#71]
I think I'll just make a field saying other assessors. Need to check the website to see if that's a sensible thing to do.

**Comment by reupost** [comment]
Sounds good.  Can we push this up the priority-list a bit, please?  That way the reptile assessments can be completed.

**Comment by rukayaj** [comment]
Ok take a look, I've added the field in, it's got 255 char limit. That ok?

**Comment by reupost** [comment]
I think that should be fine
