### ISSUE TITLE
Edit permissions

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#74]
Feedback from user: "Users authorised for their area of speciality must be able to edit their entries. At the moment all registered users can edit edit all entries."

**Comment by reupost** [comment]
This is not true of normal users (i.e. taxon experts) who can only edit their own content.  The taxon lead-type users have permission to edit everything, but to change this they would need an attribute to set their area of speciality (e.g. mammals, birds), and permissions would need to be set on that basis.  That would be a fairly significant effort.  At present all users are set as 'Taxon leads' - this was discussed at the workshop: I would move to put most users into the 'normal user' role.

**Comment by rukayaj** [comment]
Ok, well for the moment I've just set all users to be normal users/taxon experts. I am surprised that they don't trust their colleagues not to edit their content - presumably it is a trust problem? I'd suggest that this functionality gets implemented in the future if there is a huge problem with people editing other people's species "illegally" (and I'll eat my hat if there is). It does make a new revision of content each time something's edited anyway.
