### ISSUE TITLE
The user can leave the page without validation

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#8]
Give clear instructions ensuring the user provides the evidence before they are able to save and leave the page.

**Comment by rukayaj** [comment]
I think this actually causes problems as well - I can just see people putting "Placeholder" in the justification and references box because they want to save their progress so far and are frustrated that they can't. This could potentially be something the Taxon Leads police, what do you think?

**Comment by rukayaj** [comment]
What we could do is make the wording on the box stronger (like add MANDATORY in capital letters or something)?

**Comment by reupost** [comment]
I think its fine to leave this as something the taxon leads need to deal with, I wouldn't worry about changing the text.

**Comment by rukayaj** [comment]
Ok great.
